### ISSUE TITLE
Issue with using installer (error: undefined method `[]' for nil:NilClass.)

### ISSUE THREAD

**Issue by marklonquist** [DragonBox/u3d#138]
```
PS C:\Windows\system32> u3d install 2017.1.0f3 -p Unity,Android,Windows --trace
Root privileges are required
Unity is already downloaded
Android is already downloaded
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/downloader.rb:167:in `destination_for': undefined method `[]' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/downloader.rb:98:in `get_package'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/downloader.rb:52:in `block in download_modules'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/downloader.rb:51:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/downloader.rb:51:in `download_modules'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/downloader.rb:40:in `fetch_modules'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/commands.rb:132:in `install'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/commands_generator.rb:147:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/commands_generator.rb:195:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/lib/u3d/commands_generator.rb:37:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/u3d-1.0.3/exe/u3d:7:in `<top (required)>'
        from C:/Ruby24-x64/bin/u3d:22:in `load'
        from C:/Ruby24-x64/bin/u3d:22:in `<main>'
PS C:\Windows\system32>
```

**Comment by marklonquist** [comment]
Seems this could because I'm running it on a windows machine.. Should perhaps not throw an error because of this, and just skip it?

**Comment by lacostej** [comment]
Maybe because Windows isn't a package available on Windows. We should filter them out before trying to install. Thanks for the bug report!

**Comment by lacostej** [comment]
@marklonquist I made it so that it fails. As it's the same mechanism that will catch someone asking to install package `Lniux` instead of `Linux`, I preferred to make it fail hard for now, in an explicit manner. We could consider making it ignore unknown modules, but I think it might hide user mistakes unnecessarily. WDYT?

**Comment by marklonquist** [comment]
@lacostej the hard fail is great, as it gives a reason to what the issue is.. Perhaps also add a "-skip-modules" argument (you may be able to think of a better work)? Just a suggestion :-)

**Comment by lacostej** [comment]
@marklonquist I am not sure I understand how you want the `-skip-modules` to work? 

u3d already has the ability to install just the core (except on Linux where it doesn't install modules).

Or did you mean something like `-skip-non-existing-modules`? If so, out of curiosity, how would you use it?  I am asking because in my head, if you specify the wrong module name, then you are probably not doing what you intended to do. So if we add an option so that u3d doesn't fail, the user might get the wrong impression that things worked, while it didn't. It might make you lose more time than correcting your argument line.

**Comment by marklonquist** [comment]
It was just a quick thought :-) But yea, it was the "-skip-non-existing-modules" variant I was looking for, but no, it's not really needed. So the hard fail is exactly what was needed I'd guess.

**Comment by lacostej** [comment]
Cool. Feedback really appreciated.

Note: you're our first external bug reporter on github. Achievement unlocked! ;)

**Comment by marklonquist** [comment]
Glad I could help :) You can close this whenever you believe it's completely done.
