### ISSUE TITLE
No Beta versions visible with u3d available

### ISSUE THREAD

**Issue by Skjalgsm** [DragonBox/u3d#330]
### Issue Checklist

- [x ] I'm using the latest u3d version
- [ x] I ran `u3d --help`
- [ x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [ x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

u3d available or u3d available --no-central does not list beta versions. If this is intended, how can I use u3d to install the latest beta version? (which at the moment is Unity 2018.3.0b8)

**Comment by langtind** [comment]
I think this is related to #314.

**Comment by Skjalgsm** [comment]
Yep

https://github.com/sttz/install-unity/tree/next/Command


fre. 30. nov. 2018 kl. 18:28 skrev Paul Niezborala <notifications@github.com

**Comment by niezbop** [comment]
Thanks for the link!

So it seems that Unity has taken down beta availability. Even their own links on the new beta pages to the beta archives redirect to the newer beta.
I have started fiddling around with the ability to fetch unity installs from custom places so that you could pass your desired locations, and that looks rather easy to do, so expect a PR if you are still interested in u3d 😄
