### ISSUE TITLE
[Feature request] Installing package into existing installations

### ISSUE THREAD

**Issue by exlee** [DragonBox/u3d#71]
It would be great if I could add module/package to existing installation without removing it first.

(It caches the files, but what if the cache wouldn't be there, would I have to redownload everything?)

**Comment by niezbop** [comment]
This feature is supposed to be working right now.
Running `u3d install 5.6.0f3` followed by `u3d install 5.6.0f3 -p iOS` should install Unity 5.6.0f3 and add iOS without having to install it.

If this feature is not working properly on your machine, it may be linked to you other issue #69 because u3d fails to detect the version, and therefore cannot add the module correctly.
